name: build-web-image-workflow
on: [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker image build -t ondrejneufinger/web:ch09 web

